server:
  port: 8081

############################################################
# Kafka properties
############################################################
kafka:
  bootstrapAddress: 127.0.0.1:9092
  topic: temporary_topic

############################################################
# Stock market generated quotes properties
############################################################
stock:
  market:
    unique:
      quotes: 30
    schedule: "500"

############################################################
# Logging level
############################################################
logging:
  level:
    com:
      university: debug
