server:
  port: 8081

############################################################
# Kafka properties
############################################################
kafka:
  bootstrapAddress: 127.0.0.1:9092
  topic: stock_test

############################################################
# TwelveData webservice properties (twelvedata.com)
############################################################
twelvedata:
  webservice:
    enable: true
    properties:
      keyPassword: ${api.key} #Here add your api secret key
      url: wss://ws.twelvedata.com/v1/quotes/price
      subscribeSymbols: AAPL,INFY,TRP,QQQ,IXIC,EUR/USD,USD/JPY,BTC/USD

############################################################
# Stock market generated quotes properties
############################################################
stock:
  market:
    unique:
      quotes: 30
    schedule: "500"

############################################################
# Logging level
############################################################
logging:
  level:
    com.university.stock.producer: debug
