package com.university.stock.market.model.domain;

public enum Sector {
  ENERGY_MINERALS,
  CONSUMER_NON_DURABLES,
  UTILITIES,
  ELECTRONIC_TECHNOLOGY,
  HEALTH_SERVICE,
  FINANCE,
  COMMUNICATIONS,
  TRANSPORTATION,
  RETAIL_TRADE,
  COMMERCIAL_SERVICES,
  TECHNOLOGY_SERVICES,
  CONSUMER_DURABLES;
}
