server:
  port: 8081


producer:
  ############################################################
  # Kafka properties
  ############################################################
  kafka:
    enable: false
    bootstrapAddress: 127.0.0.1:9092
    topic: stock_test

  ############################################################
  # AWS Kinesis properties
  ############################################################
  kinesis:
    enable: true
    aws:
      region: us-east-1
      stream: stock_test
      access:
        key: ${aws.access.key} #Here add your AWS access key
      secret:
        key: ${aws.secret.key} #Here add your AWS secret key

############################################################
# TwelveData webservice properties (twelvedata.com)
############################################################
twelvedata:
  webservice:
    enable: true
    properties:
      keyPassword: ${api.key} #Here add your api secret key
      url: wss://ws.twelvedata.com/v1/quotes/price
      subscribeSymbols: AAPL,INFY,TRP,QQQ,IXIC,EUR/USD,USD/JPY,BTC/USD

############################################################
# Stock market generated quotes properties
############################################################
stock:
  market:
    unique:
      quotes: 30
    schedule: "500"

############################################################
# Logging level
############################################################
logging:
  level:
    com.university.stock.producer: debug
