server:
  port: 8082
application:
  name: stock-stream-processing-app

############################################################
# Kafka properties
############################################################
kafka:
  bootstrapAddress: 127.0.0.1:9092
  topic:
    stock: stock_test
    intermediary: stock_status_intermediary_test
    statistic: stock_status_test

############################################################
# Trading analysis module properties
############################################################
trading:
  maximumBars: 400
  tradeDurationInMillis: 100

############################################################
# Logging level
############################################################
logging:
  level:
    com.university.stock.processing.streams: debug